### ISSUE TITLE
Install private repo from git

### ISSUE THREAD

**Issue by SmritikaS** [aws-samples/aws-cost-explorer-report#18]
build.sh does not work, in case requirements.txt has referenced a private repo from git. 
In this case, we need to add git credentials or ssh, in order for this to work.

**Comment by davfaulk** [comment]
I dont follow this issue? build requires Docker, and access to public amazonlinux and PIP repositories only as far as I can tell. Build is also only required to get more recent PIP libraries... So in most cases, you shouldn't need to use build at all anyway.
