### ISSUE TITLE
deploy.sh script expects artifacts from author's local machine

### ISSUE THREAD

**Issue by lazzarello** [aws-samples/aws-cost-explorer-report#24]
line 21 of `deploy.sh` expects something that is local to the computer that belongs to the author of this utility. I think it's easy to fix but noting here before I get into debugging. Likely will follow up with a PR.

*update* There is also the AWS account ID of @davfaulk which was added on 2019-06-13 and not removed. It appears the ARN of the dependency layer doesn't have public readable permissions. I'm getting a 403 for `arn:aws:lambda:us-east-1:749981256976:layer:aws-cost-explorer-report:1`

**Comment by lazzarello** [comment]
I got the script to work. I've updated documentation and some of the files but I can't make a pull request here because this work does not have an open source license. I have a fork on my personal Github, if anyone comes across this issue and wants to see my changes.

https://github.com/lazzarello/aws-cost-explorer-report/tree/for-astra

**Comment by eKuG** [comment]
@lazzarello The issue that you described above is still persisting for me.
I'm getting a 403 for arn:aws:lambda:ap-south-1:749981256976:layer:aws-cost-explorer-report:1

Can you please tell how to do it. I changed my region in all the files. Went in to the terminal, and executed sh deploy.sh
Am I missing something?
Can you please guide me?
I even forked your repo: https://github.com/lazzarello/aws-cost-explorer-report/tree/for-astra

**Comment by davfaulk** [comment]
Fixed. Created a layer binary, and moved to public read s3 bucket.
