### ISSUE TITLE
issue easy deploy

### ISSUE THREAD

**Issue by dmartinezrubio** [aws-samples/aws-cost-explorer-report#28]
I always received this message (us-east-1):

"Your access has been denied by S3, please make sure your request credentials have permission to GetObject for aws-cost-explorer-report-bin/lambda.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 87e94822-4462-4241-a082-dabe4f05cb70; Proxy: null)"

Did I have to create previosly an S3 with specific permission?

**Comment by davfaulk** [comment]
Binaries now moved to a location with read access. The other alternative is to run build.sh, but depends on Docker on Mac or Linux x86.
