### ISSUE TITLE
Show/exclude credits from report

### ISSUE THREAD

**Issue by grusy** [aws-samples/aws-cost-explorer-report#3]
It would be create to have an option to show or exclude applied credits from the report.

**Comment by davfaulk** [comment]
Hi Martin. I think I have added this support - but as I don't actually have credits / refunds in my account, due you mind helping test? Use branch exclude_credits :) Otherwise I'm going to try find an account with credits to test with, before pulling into master.

**Comment by xsm74** [comment]
Hi David,
I will check this today and update you
