### ISSUE TITLE
AWS account aliases

### ISSUE THREAD

**Issue by cgbasm** [aws-samples/aws-cost-explorer-report#39]
Is it possible to have the report created using the account aliases rather than the account name? I've tried working this in the paginator but whenever I make a change in there the report will just return the account ID.

**Comment by yunpengeric** [comment]
Hi @cgbasm 
My understanding is the account name and the account alias are the same thing.
Just make sure the lamda environment variable `AccountLabel = Name`.

**Comment by cgbasm** [comment]
Oh my, I feel pretty dumb there. I had AccountLable = Email....no name. Thank you for pointing that one out. That was the issue.
