### ISSUE TITLE
Default reports for last day of previous month from run date

### ISSUE THREAD

**Issue by xsm74** [aws-samples/aws-cost-explorer-report#5]
At present the default behaviour is for the reports using the last day of current month, 

Billing is generally finalised around the 5th of the month however we should not need the current partial month when generating the reports as this will always show as a cost delta reduction 

we will need to offset the data culation in lambda.py to be last month to give a more accurate representation

**Comment by grusy** [comment]
If you set the end date back to last month, you have to reduce the reporting to the last 11 months, as the api can't go back further than 1 year.

https://github.com/aws-samples/aws-cost-explorer-report/pull/6

**Comment by davfaulk** [comment]
api can go back more than 1 year, but not for RI usage calls. So am tweaking this PR, and will manually merge. Also adding a flag so you can opt in or out of current month, default to opt out.
