### ISSUE TITLE
Alternate zip storage?

### ISSUE THREAD

**Issue by QuinnyPig** [aws-samples/aws-cost-explorer-report#8]
Would it be possible to shove the zip file into something that isn't git (say, an S3 bucket / git-lfs / etc)? Right now the repo is 61MB and growing with every new zip file regeneration.

**Comment by davfaulk** [comment]
Yes. Good idea / agreed. Will implement as part of next push/merge - and will look to do a filter-branch to remove the file history. Something I overlooked in haste to release something deploy-able.

**Comment by QuinnyPig** [comment]
Completely understandable; I was just somewhat surprised with a fresh clone (new environment) over a somewhat dodgy connection. This is the kind of problem that only gets worse with time...

**Comment by davfaulk** [comment]
Done. Repo should be much lighter weight now.
